### ISSUE TITLE
Add ability to include Unpublished to Proofs

### ISSUE THREAD

**Issue by tempsaint** [bmlt-enabled/bmlt-portal#7]
Request the ability to include unpublished meetings to the proof reports. Preferably as an clickable option and not have to change the config.php to do it, but I'll take what I can get.  Also, hopefully, the report would list them separately or distinguish them from published meetings.

**Comment by pjaudiomv** [comment]
I have added this to the proofs page, there is a link at the top to toggle between published and unpublished meetings. this was the easiest way to do it to get them split up. alternatively i could have them all be on one page but they will be mixed to gether except unpublished meetings will have unpublished in parenthesis next to meeting name.

**Comment by tempsaint** [comment]
It works! 
Just because I'm curious how it would look to have the unpublished mixed in, I'd love to see the option. Which brings up another issue... (sorry)

**Comment by pjaudiomv** [comment]
I added an option to show both, you just have to change the unpublished query string parameter to both example https://ctna.org/changes/proofs.php?asc=Central Connecticut Area&areanum=2&unpublished=both

**Comment by tempsaint** [comment]
This works great. I'm not sure if you planned on adding a toggle up top or just relying on knowing that you have to change the option to "both"

**Comment by pjaudiomv** [comment]
not planning on adding one your the only one who requested this feature. whatever way you like ill just make that the default for the unpublished toggle

**Comment by tempsaint** [comment]
Ok. Leave it the way it is then. I'll try to remember.

**Comment by pjaudiomv** [comment]
cool
