### ISSUE TITLE
Sort proof in alternate ways

### ISSUE THREAD

**Issue by tempsaint** [bmlt-enabled/bmlt-portal#8]
Can we adjust the proof to display meetings by day/time instead of alphabetical by meeting name?  I like having options... maybe have a toggle like you did for show unpublished?

**Comment by pjaudiomv** [comment]
I added an option to show both, you just have to change the `unpublished` query string parameter to `both` example `https://ctna.org/changes/proofs.php?asc=Central Connecticut Area&areanum=2&unpublished=both`

**Comment by pjaudiomv** [comment]
I added a sort by day/time with a similar toggle and is in main branch now.

**Comment by tempsaint** [comment]
You're awesome!
